### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by celsoricardoweb** [johnsondotle/Instagram-Non-followers#1]
![SNAG-0000](https://user-images.githubusercontent.com/118099086/218996181-e751db0b-a8aa-40e6-8709-5399004d8ce3.jpg)

**Comment by johnsondotle** [comment]
1. Instagram renamed the file from the original "followers.json" to "followers_1.json"
Solution: Rename the file to "followers.json" again.

2. Instagram removed the list name "relationships_followers" in the "followers.json" file.
Solution: Add the list name "relationships_followers" and it's proper brackets again into the file.

1a) Before: Renaming
![Image 1 for Problem 1](https://user-images.githubusercontent.com/75176300/223276994-b139f8ca-eba3-4f0a-95f2-4ce75aab33a3.png)

1b) After: Renaming
![Image 2 For Problem 1](https://user-images.githubusercontent.com/75176300/223276996-13b8c3c6-2527-445a-a470-f800527158f1.png)

2a) Before: Adding list name and brackets at the beginning
![Image 1 For Problem 2](https://user-images.githubusercontent.com/75176300/223277110-b55e22ed-51f2-4c98-9133-622acc7bcc95.png)

2b) After: Adding list name and brackets at the beginning
![Image 2 For Problem 2](https://user-images.githubusercontent.com/75176300/223277111-0d085c9d-5e57-4c25-9978-7bbf3abbaf9d.png)

2c) Before: Adding brackets at the end
![Image 3 For Problem 2](https://user-images.githubusercontent.com/75176300/223277112-6e00b521-2474-4aa7-99d3-f14dd44cb1b9.png)

2d) After: Adding brackets at the end
![Image 4 For Problem 2](https://user-images.githubusercontent.com/75176300/223277115-8ebc7ed7-a8d5-4a6c-89f6-f971c250af41.png)
